export { default as SUPPORT } from "./pages/support/index";
export { default as LOGIN } from "./pages/login/Login";
export { default as REGISTRATION } from "./pages/registration/register";
export { default as CURRENTAFFAIRS } from "./pages/currentAffairs/currentAffairs";
export { default as COURSES } from "./pages/courses/courses";
export { default as LIVECLASSES } from "./pages/liveClasses/liveClasses";
export { default as TESTSERIES } from "./pages/testSeries/testSeries";
export { default as STUDYMATERIAL } from "./pages/studyMaterial/studyMaterial";
export { default as PREVYEARPAPER } from "./pages/Prev Year Papers/PrevYearPapers";
export { default as MYPROFILE } from "./pages/myPfofile/myProfile";
export { default as COURSECATEGORIES } from "./pages/mySubscription/subMySubscription/courseCategory/courseCategories";
export { default as COURSEDEATAILTWO } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/coursedetailsTwo";
export { default as VIDEOPANNEL } from "./pages/mySubscription/subMySubscription/videoPannel/videoPannel";
export { default as PACKAGE } from "./pages/courses/package/Package";
export { default as ERRORPAGE } from "./pages/errorpage/ErrorPage";
export { default as COURSEDETAILONE } from "./pages/courses/coursedetailsone/courseDetailsOne";
export { default as LAYOUT } from "../components/Layout/layout";
export { default as LIVEPANNEL } from "./pages/liveClasses/livepanel/livePanel";
export { default as TESTSERIESEXPLORE } from "./pages/testSeries/testexplore/testseriesexplore";
export { default as TESTSERIESATTEMPT } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testseriesAttempt/testseriesAttempt";
export { default as TESTSERIESREPORT } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testseriesreport/testseriesreport";
export { default as TESTSOLUTION } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testseriesreport/testSolution";
export { default as FORGOTPASS } from "./pages/login/forgetpassword";
export { default as SUBSCRIPTION } from "./pages/mySubscription/mySubscription";
export { default as VIDEO_LECTURES } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/videoLectures"
export { default as TEST_SERIES_TAB } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testSeriesTab"
export { default as PDF_NOTES_TAB } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/PdfNotesTab"
export { default as HEADER } from "../components/Layout/header"
export { default as SIDEBAR } from "../components/Layout/sidebar"
export { default as FOOTER } from "../components/Layout/footer"
export { default as TEST_QUESTIONS } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testseriesAttempt/testQuestions"
export { default as TEST_TIMER } from "./pages/mySubscription/subMySubscription/coursedetailsTwo/testseriesAttempt/testTimer"
export { default as PRICE_DETAIL } from "./pages/courses/package/priceDetails"
export { default as BACK_KEY } from "../components/Back key/backKey"
export { default as LOADER } from "../components/loader/Loader"
export { default as PACKAGE_DETAILS } from "./pages/courses/package/packageDetails"
export { default as SCROLL_TABS } from "../components/scrollTabs/scrollTabs"
export { default as COURSE_CARD } from "./pages/courses/card"
export { default as COMING_SOON } from "../components/upcomming/comingSoon"
// export {default as LIVE_CLASS_CARD} from "./pages/liveClasses/liveClassCard"